### ISSUE TITLE
get_streaming_mask function not found in this project

### ISSUE THREAD

**Issue by ArtemisZGL** [ZhengkunTian/OpenTransformer#1]
i found some module name error and fix some of them, but i can't found get_streaming_mask function in the util scrip. Besides, should i download the aishell data and push it in the egs/aishell/data ? Because i met the error 'no engs/aishell/data/vocab' as well.

**Comment by ArtemisZGL** [comment]
and i think is that the dataset you used for aishell is processed by the espnet script using kaldi ?

**Comment by ZhengkunTian** [comment]
Sorry, I have fixed it!
