### ISSUE TITLE
训练集上表现很好，但是在验证集上测试会缺少前面一到两个字。

### ISSUE THREAD

**Issue by RulerOne** [ZhengkunTian/OpenTransformer#11]
BAC009S0724W0121 市 房 地 产 中 介 协 会 分 析
BAC009S0724W0122 市 房 地 产 中 介 协 会 还 表 示
BAC009S0724W0123 于 其 他 一 线 城 市
BAC009S0724W0124 二 手 住 宅 市 场 表 现 一 举 相 对 稳 健
BAC009S0724W0125 在 股 市 大 幅 震 荡 的 环 境 下
BAC009S0724W0126 第 三 季 度 将 陆 续 有 部 分 股 市 复 兴 城 归 楼 市
BAC009S0724W0127 受 贿 六 条 及 二 套 房 首 付 七 成 的 制 约
BAC009S0724W0128 年 楼 市 等 市 房 能 回 到 快 速 上 升 通 道 依 然 存 在 变 数
BAC009S0724W0129 月 秀 区 找 回 领 先
BAC009S0724W0130 区 的 签 约 面 积 在 豪 宅 交 投 增 多 的 大 动 向 上 升 较 快
BAC009S0724W0131 天 货 区 增 长 幅 度 近 百 分 之 三
BAC009S0724W0132 万 平 方 米 的 刚 需 呼 醒 成 交 费 额 下 降 一 个 百 分 点

使用的是DDP 2张P100，batch size设置的是24。300个epoch，验证的时候选的epoch分别为50,150,296，损失已经降到了0.03左右，都是这种情况。这种现象如何解释呢？

**Comment by ZhengkunTian** [comment]
不适用DDP模式就行了，这种我没有跑过实验，我也没有遇到过同样的问题。其他模式下没有这个问题。

**Comment by ZhengkunTian** [comment]
如果你能解决，还希望告知一下，之前并没有人提到过类似问题。
