### ISSUE TITLE
lm error

### ISSUE THREAD

**Issue by wbgxx333** [ZhengkunTian/OpenTransformer#14]
the otrans/model/lm.py#L19 : 
  super(TransformerLanguageModel, self).__init__()
  self.params = params;

otrans/data.py#L236 
   src_unit2idx[c] -----------> unit2idx[c]

**Comment by ZhengkunTian** [comment]
感谢谷哥，问题已经修复

**Comment by wbgxx333** [comment]
等我跑完结果，我告诉你哈。

**Comment by ZhengkunTian** [comment]
> 等我跑完结果，我告诉你哈。

好的谷哥

**Comment by sayanxtreme** [comment]
I trained a LM on AISHELL-1 train using the default transformer_lm.yaml (60 epochs)
With beam width 10 and no LM, I got AISHELL-1 test CER 8.1
But, with the LM, CER increased to 8.99
@wbgxx333 @ZhengkunTian did you face this? How much improvement can be expected from the LM?
