### ISSUE TITLE
LM trained increased CER

### ISSUE THREAD

**Issue by smandal94** [ZhengkunTian/OpenTransformer#18]
I trained a LM on AISHELL-1 train using the default transformer_lm.yaml (60 epochs)
With beam width 10 and no LM, I got AISHELL-1 test CER 8.1
But, with the LM, CER increased to 8.99
@ZhengkunTian  did you face this? How much improvement can be expected from the LM?

**Comment by ZhengkunTian** [comment]
Do you average the parameters of the language model? I got an absolute improvement of about 0.2.  I updated the model configuration file, you can try again. Don't forget to average the model parameters.

**Comment by wbgxx333** [comment]
what is your lm model loss? @sayanxtreme   
with the lm, @ZhengkunTian is ok.

**Comment by smandal94** [comment]
@wbgxx333 Average Loss was 11.5 at epoch 60 and I had continued till epoch 120 where loss was 5.02

**Comment by wbgxx333** [comment]
maybe you need change the default configure.the loss is about 1.
