### ISSUE TITLE
Grad norm is NAN after epoch 52

### ISSUE THREAD

**Issue by jjjjohnson** [ZhengkunTian/OpenTransformer#22]
@ZhengkunTian 代码很棒！请教一下 Grad norm is NAN 这种情况在Global Step:12450 之后就频繁出现，在step：12450之前的loss都是稳定下降的，感觉也不像是不收敛。请问有遇到这种情况吗？

![image](https://user-images.githubusercontent.com/20569095/100822866-21ae3f00-348e-11eb-8240-6c823c8897ef.png)

谢谢！

**Comment by jjjjohnson** [comment]
我用了mixed_precision 训练。 我猜可能和这个原因有关。

**Comment by ZhengkunTian** [comment]
恩恩，混合精度训练这块我还没有做大量的实验进行证明研究，梯度为NAN应该是混合精度造成的，这部分内容可以参考pytorch tutorial中的混合精度部分，里面可以分别设置哪一部分使用半精度，这个估计比nvidia的apex效果稳定一些



发件人: JUNJIE JIN<mailto:notifications@github.com>
发送时间: 2020年12月2日 11:22
收件人: ZhengkunTian/OpenTransformer<mailto:OpenTransformer@noreply.github.com>
抄送: ZhengkunTian<mailto:zhengkuncasia@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [ZhengkunTian/OpenTransformer] Grad norm is NAN after epoch 52 (#22)


我用了mixed_precision 训练。 我猜可能和这个原因有关。

―
