### ISSUE TITLE
想要提升解码速度

### ISSUE THREAD

**Issue by nangongmujd** [ZhengkunTian/OpenTransformer#23]
想要保证精度的情况下进一步提升解码速度,请问有什么建议吗?

**Comment by ZhengkunTian** [comment]
解码过程中存在一些冗余计算，可以通过缓存这部分来提升速度。现在的速度基本上就是并行速度上限了，再提升可以考虑模型量化，或者使用C++对这部分进行重写。

**Comment by nangongmujd** [comment]
好的，谢谢！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ZhengkunTian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月18日(星期五) 晚上9:21
收件人:&nbsp;&quot;ZhengkunTian/OpenTransformer&quot;<OpenTransformer@noreply.github.com&gt;;
抄送:&nbsp;&quot;nangongmujd&quot;<201383353@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhengkunTian/OpenTransformer] 想要提升解码速度 (#23)
