### ISSUE TITLE
Missing classes in otrans.module.pos

### ISSUE THREAD

**Issue by jiamingkong** [ZhengkunTian/OpenTransformer#33]
Hi, I am trying to train a Conformer model. The run.py ran successfully, however while trying to evaluate the model, I realized the missing classes`MixedPositionalEncoding` and `RelPositionalEncoding`  in `otrans.module.pos`. I will have to rewind back to commit c636e43 to find the definition of these classes. So in the current version, the eval.py won't run. 

Thanks

**Comment by ZhengkunTian** [comment]
These two class has been removed. I unify the functions into a new class named PositionalEncoding.

**Comment by jiamingkong** [comment]
Hi, thank you for your reply. I followed your hint and tried to run the `eval.py`. However I ran into the following issue:

Here is what I did:

1. otrans/encoder/__init__.py
    I commented out the BuildEncoder["transformer"] and the import as the TransformerEncoder is not useful in this situation, and it depended on `MixedPositionalEncoding`.
2. Run `eval.py`

    After successfully trained the models following configurations given in egs/aishell-1, loss of the conformer baseline model is about 0.5 and that of the LM is also quite low.
   So I plugged them in the eval.py again. And I realized the `ConformerEncoder` class didn't have the `inference` method implemented. The code commented out was pointing to the original implementation of PositionalEncoding.
The call hierarchy to this function is:
```
eval.py --> o/recognizer/speech2text.py/SpeechToTextRecognizer.model.encoder.inference on line 29.
```

3. Reimplement `ConformerEncoder.inference(x, mask, cache=None)`

I read through the code and reimplemented the inference function following the forward function:

```python
    def inference(self, x, mask, cache=None):
        
        if self.relative_positional:
            enc_output = x
            # [1, 2T - 1]
            position = torch.arange(-(x.size(1)-1), x.size(1), device=x.device).reshape(1, -1)
            pos = self.pos_emb._embedding_from_positions(position)
        else:  
            enc_output, pos = self.pos_emb(x)

        x.masked_fill_(~mask.unsqueeze(2), 0.0)

        attn_weights = {}
        new_caches = []
        for i, block in enumerate(self.blocks):
            x, new_cache, attn_weight = block.inference(x, mask, pos, cache[i] if isinstance(cache, list) else cache)
            new_caches.append(new_cache)
            attn_weights['enc_block_%d' % i] = attn_weight

        return x, mask, new_caches, attn_weights
```

4. Now the eval.py runs. However the results are quite problematic: it repeats a few random characters:

```
- pred- 0 (-1.4451) : <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
 - pred- 0 (-1.3312) : 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话 话
```

I am wondering if you have any idea that I can fix this issue. Thanks! I really appreciate this git as it provided a conformer functionality without the need for a complex setup process like ESPnet.

**Comment by ZhengkunTian** [comment]
I update the code last night. I also noticed the same problem. The new version is effective.

**Comment by ZhengkunTian** [comment]
I updated the code last night. I also noticed the same problem. The new version is effective.
