### ISSUE TITLE
The conformer recipe still doesn't run

### ISSUE THREAD

**Issue by jiamingkong** [ZhengkunTian/OpenTransformer#35]
Hi, thanks so much for the code update. However, I still haven't been successful in completing the "train and eval" recipe as shown in readme.md. Here is a few problems I found along the way:

Suppose one decides to run the `eval.py` with -m and -lm supplied:

1. The `otran/recognize/speech2text.py`:
    SpeechToTextRecognizer.encode() will call the `SpeechToTextRecognizer.model.encoder.inference()` function, accepting 3 parameters. However the `Conformer.inference()` function will return 4 parameters:
```python
       # conformer.inference
       return enc_output, mask, new_caches, attn_weights
```

This should be an easy fix, I changed the code to :

```python
# speech2text.SpeechToTextRecognizer.encode()
memory, memory_mask, enc_cache, enc_attn_weights = self.model.encoder.inference(inputs, inputs_mask, cache['encoder'] if cache is not None else None)
```

2. The `otrans/model/lm.py`

    The positionalEncoding in the TransformerLanguageModel will be called in `TransformerLanguageModel.forward()` on line 130. The code said:

```python
    dec_output = self.pos_embedding(dec_output)
```

While the PositionalEncoding class will actually return `return self.dropout(x), posemb`, two parameters.  I changed the code to:

```python
    dec_output, _ = self.pos_embedding(dec_output)
```
just to ignore the posemb output.

3. otrans/encoder/transformer.py

In the forward() of TransformerEncoderLayer, the return type is x: torch.Tensor, and mask: dict. The dictionary can't be feed into other operations directly.

After fixing the above problems, the inference still doesn't work. I got results that were neither empty, nor repeating the same character to a fixed length.

**Comment by jiamingkong** [comment]
Some of these issues were only found while I was trying to perform an evaluation. I have two models trained to very low loss and would definitely love to help debugging. Thanks!

**Comment by ZhengkunTian** [comment]
Oh, sorry about it. I forget to update the inference code. Thanks for your check.

**Comment by ZhengkunTian** [comment]
If you find any error, please tell me or report a PR. Thanks a lot!
