### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by jjjjohnson** [ZhengkunTian/OpenTransformer#36]
你好

[这个函数没有用到](https://github.com/ZhengkunTian/OpenTransformer/blob/adab2960946762a5d3806d4299aee1dfcd6f0538/otrans/encoder/conformer.py#L55) 按照conformer 文章中应该在 Convolution Module 之后用的。希望答疑。

谢谢！

**Comment by ZhengkunTian** [comment]
感谢 这个很关键 谢谢！

**Comment by jjjjohnson** [comment]
你代码写的很棒！向你学习！

**Comment by ZhengkunTian** [comment]
感谢 多多交流！
