### ISSUE TITLE
Fixing language model

### ISSUE THREAD

**Issue by jiamingkong** [ZhengkunTian/OpenTransformer#37]
Hi, I wish you all the best in the year of Ox, may the force be with you.

So as I am experimenting with more of your code, I realize the repeating character bug was actually caused by the #36 and I came up with the same fix as the other programmer proposed. However I saw there is still something off in the `lm.py`:

I will just post the fixed `predict()` in TransformerLanguageModel below for your reference:

```python
# lm.py-> TransformerLanguageModel.predict()

    def predict(self, targets, last_frame=True):

        dec_output = self.embedding(targets)

        # Fix 1: PositionalEncoding return self.dropout(x), posemb
        dec_output, _ = self.pos_embedding(dec_output)

        dec_mask = get_seq_mask(targets)

        for _, block in enumerate(self.blocks):
            # Fix 2:
            # block = TransformerEncoderLayer, return x, {'slf_attn_weights': slf_attn_weights}
            dec_output, _ = block(dec_output, dec_mask)

        if self.normalize_before:
            dec_output = self.after_norm(dec_output)

        logits = self.output_project(dec_output)

        if last_frame:
            log_probs = F.log_softmax(logits[:, -1, :].unsqueeze(1), dim=-1)
        else:
            log_probs = F.log_softmax(logits, dim=-1)

        return log_probs
```

There were two fixes, seemed like the return type didn't match after you tried to cache some of the parameters in the effort of complexity reduction. With the fixes above the code should run. That's it.

Happy new year!

**Comment by ZhengkunTian** [comment]
Thanks a lot. I have fixed it as your advice. Happy new year!
