### ISSUE TITLE
用AISHELL1数据集训练后，测试集解码出来的文字总是重复的几句话。

### ISSUE THREAD

**Issue by baozixifan** [ZhengkunTian/OpenTransformer#4]
/test
BAC009S0764W0121 根 据 中 原 地 产 研 究 部 统 计
BAC009S0764W0122 根 据 中 原 地 产 研 究 部 统 计
BAC009S0764W0123 根 据 中 原 地 产 研 究 部 统 计
BAC009S0764W0124 根 据 中 原 地 产 研 究 中 心 的 统 计 数 据
BAC009S0764W0125 根 据 中 原 地 产 研 究 部 统 计
BAC009S0764W0126 楼 市 成 交 量 有 所 回 暖
BAC009S0764W0127 根 据 中 原 地 产 市 场 研 究 部 统 计
BAC009S0764W0128 楼 市 成 交 量 大 幅 下 降
BAC009S0764W0129 楼 市 成 交 量 大 幅 下 降
BAC009S0764W0130 根 据 中 原 地 产 研 究 中 心 的 统 计 数 据
BAC009S0764W0131 根 据 中 原 地 产 研 究 中 心 的 统 计 数 据
BAC009S0764W0132 楼 市 成 交 量 大 幅 下 降
BAC009S0764W0133 楼 市 成 交 量 大 幅 下 降
BAC009S0764W0134 根 据 中 原 地 产 研 究 部 统 计
BAC009S0764W0135 根 据 中 原 地 产 研 究 部 统 计
BAC009S0764W0136 根 据 中 原 地 产 研 究 中 心 的 统 计 数 据

训练轮数不一样，得出的文字不一样，但是输出数据中基本都是几条重复的语句。
请问下，这是因为我训练或者测试中有哪里设置错误了吗？

**Comment by ZhengkunTian** [comment]
这个是在多少轮的时候解码的，什么模型配置

**Comment by baozixifan** [comment]
data:
  name: aishell
  vocab: egs/aishell/data/vocab
  batch_size: 16
  text: text
  train: egs/aishell/data/train
  test: egs/aishell/data/test
  dev: egs/aishell/data/dev
  short_first: False
  num_mel_bins: 40
  apply_cmvn: False
  normalization: True
  spec_argument: True
  left_frames: 0
  right_frames: 0
  skip_frames: 0
  from_kaldi: False
  num_works: 4
model:
  # network architecture
  type: transformer
  d_model: 256
  normalize_before: False
  concat_after: False
  # dropout
  pos_dropout_rate: 0.0
  ffn_dropout_rate: 0.0
  slf_attn_dropout_rate: 0.0
  src_attn_dropout_rate: 0.0
  residual_dropout_rate: 0.1
  # encoder related
  feat_dim: 40
  num_enc_blocks: 6
  enc_ffn_units: 1024
  enc_input_layer: conv2d
  # decoder related
  vocab_size: 4250
  num_dec_blocks: 6
  dec_ffn_units: 1024
  # attention related
  n_heads: 4
  # label smoothing
  smoothing: 0.1
  activation: glu
  share_embedding: True
train:
  scheduler: stepwise
  optimizer: adam
  warmup_steps: 12000
  shuffle: True
  lr: 1.0
  clip_grad: 5
  epochs: 50
  accum_steps: 1
  grad_noise: False
  load_model: False
  save_name: transformer
模型配置如上，总共训练了39轮，挑选其中39轮和12轮做测试，其中解码结果不一样，但基本集中为几条固定的语句。

**Comment by ZhengkunTian** [comment]
设置 accum_steps = 8 重新跑一下，现在的batch太小，模型训练不好

**Comment by baozixifan** [comment]
好的，谢谢您，我再试试，麻烦您了。

**Comment by baozixifan** [comment]
问题解决了，谢谢您！
