### ISSUE TITLE
conformer的性能如何？

### ISSUE THREAD

**Issue by dayu1979** [ZhengkunTian/OpenTransformer#40]
你好，感谢您的工作，我试图训练一个中英混合的las模型，请问conformer的性能怎么样阿？能否给一些建议

**Comment by ZhengkunTian** [comment]
您好 conformer性能应该是目前最好编码器，不过需要选择合适的参数，我并没有针对conformer进行精准的调参，大部分的实验结果都是优于transformer的，目前我尝试的最好效果没有语言模型，不适用CTC联合训练的情况下，conformer在aishell上的表现是测试集CER 5.5. 希望对您有帮助！ 祝好！
