### ISSUE TITLE
bug when load scheduler

### ISSUE THREAD

**Issue by blairstar** [ZhengkunTian/OpenTransformer#42]
In TransformerScheduler init function, 
when calling super(TransformerScheduler, self).__init__(optimizer, stepwise=True),
will execute initial_lr() ->self.step()->self.get_step_lr(step=self.global_step), 
meanwhile get_step_lr(self, step=None) is "NotImplementedError".
this will result in self.lr with None

**Comment by ZhengkunTian** [comment]
Thanks, i have fixed it.
