### ISSUE TITLE
根据ctc提取隐含层状态的实现代码在哪里呀

### ISSUE THREAD

**Issue by zhhao1** [ZhengkunTian/OpenTransformer#43]
我看到你的论文“”Spike-Triggered Non-Autoregressive Transformer for End-to-End Speech Recognition“”中根据ctc提取隐含层状态，这部分代码的实现在哪一部分呀，我没有找到。

**Comment by ZhengkunTian** [comment]
这部分代码并没有开源 实现方法很简单 通过判断CTC的尖峰位置索引 利用torch.index_select就能抽取出来了
