### ISSUE TITLE
Aishell集测试集根据默认参数训练80轮的cer仍在10%左右，和7.1%有一定差距

### ISSUE THREAD

**Issue by iamnotstory** [ZhengkunTian/OpenTransformer#5]
请问一下cer为7.1的结果是默认参数训出来的吗，是的话训练轮数是多少啊？

**Comment by ZhengkunTian** [comment]
60轮 + Spec Augment + 平均最后10轮的参数

**Comment by songtaoshi** [comment]
最后的loss也是0.2左右么，我aishell跑了100多轮，loss还是0.35

**Comment by ZhengkunTian** [comment]
> 请问一下cer为7.1的结果是默认参数训出来的吗，是的话训练轮数是多少啊？

这个原因是由于代码中存在问题，目前已经修复。按照配置跑就好了

**Comment by ZhengkunTian** [comment]
> 最后的loss也是0.2左右么，我aishell跑了100多轮，loss还是0.35

你的问题和这个不一样，你是因为对代码进行了修改导致的。
