### ISSUE TITLE
How can I get a model which can achieve the reported error rate?

### ISSUE THREAD

**Issue by mlxu995** [ZhengkunTian/OpenTransformer#6]
I have trained a model with the default settings. With total 60 training epochs, I got an error rate of 10.66%. In my experiment, I used the Fbank features extracted in the online funshion.  What else do I need to do to get the error rate in the report (7.1%) ?

**Comment by ZhengkunTian** [comment]
You should average the parameters of the last 20 epoch.

**Comment by ZhengkunTian** [comment]
You can utilize the script tools/average.py.
